#!/bin/sh

set -e

case "$1" in
    configure|abort-upgrade)
    update-alternatives --install /usr/games/doom doom \
                                  /usr/games/chocolate-doom 50 \
                        --slave /usr/share/man/man6/doom.6.gz \
                            doom.6.gz /usr/share/man/man6/chocolate-doom.6.gz
    ;;

    abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
