# Shared file included by the makefiles used to build packages.
# This contains various information needed by the makefiles,
# and is autogenerated by configure to include various
# necessary details.

# Tools needed:

CC = gcc
STRIP = strip

# Package name and version number:

PROGRAM_PREFIX = chocolate-
PACKAGE = chocolate-doom
PACKAGE_NAME = Chocolate Doom
PACKAGE_STRING = Chocolate Doom 1.6.0
PACKAGE_TARNAME = chocolate-doom
PACKAGE_VERSION = 1.6.0

# Documentation files to distribute with packages.

DOC_FILES = README       \
            COPYING      \
            ChangeLog    \
            NEWS         \
            NOT-BUGS     \
            CMDLINE      \
            TODO

